name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '22'
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all history for affected command
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Lint affected projects
        run: npx nx affected -t lint --parallel=3

      - name: Type check affected projects
        run: npx nx affected -t typecheck --parallel=3

      - name: Test affected projects
        run: npx nx affected -t test --parallel=3 --coverage

      - name: Build affected projects
        run: npx nx affected -t build --parallel=3

      - name: Upload coverage reports
        if: always()
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage
          fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Run security audit
        run: yarn audit --level moderate

      - name: Run dependency check
        run: npx nx graph --file=dependency-graph.json || true